name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths: 
      - 'Dockerfile'
      - 'src/**'
      - 'app.py'
      - 'requirements.txt'

env:
  IMAGE_NAME: betashow/gemini-deep-research

jobs:
  build-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        outputs: type=docker,dest=/tmp/gemini-deep-research.tar
        tags: ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/gemini-deep-research.tar
        retention-days: 1

    - name: Test image can start
      run: |
        docker load -i /tmp/gemini-deep-research.tar
        docker run --rm ${{ env.IMAGE_NAME }}:latest python -c "
        import sys
        print('✅ Python version:', sys.version)
        try:
            import flask, crawl4ai, google.generativeai
            print('✅ All core dependencies imported successfully')
        except ImportError as e:
            print('❌ Import error:', e)
            sys.exit(1)
        "